use_frameworks!

platform :ios, '8.0'

target 'BeesKingLib_Example' do
  pod 'BeesKingLib', :path => '../'

  target 'BeesKingLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
